# Generated by Django 2.2 on 2020-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='colores',
            field=models.ManyToManyField(related_name='AutosColores', to='crud.Colores'),
        ),
    ]
